In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
# Carregando o dataset
df = pd.read_csv('../data/brasileirao_matches.csv')

display(df.head(10))

print('Informações técnias do dataset')
df.info()

print('Valores ausentes por coluna')
print(df.isna().sum())

,datetime,home_team,home_team_state,away_team,away_team_state,home_goal,away_goal,season,round
0,2012-05-19T18:30:00Z,Palmeiras-SP,SP,Portuguesa-SP,SP,1.0,1.0,2012,1
1,2012-05-19T18:30:00Z,Sport-PE,PE,Flamengo-RJ,RJ,1.0,1.0,2012,1
2,2012-05-19T21:00:00Z,Figueirense-SC,SC,Nautico-PE,PE,2.0,1.0,2012,1
3,2012-05-20T16:00:00Z,Ponte Preta-SP,SP,Atletico-MG,MG,0.0,1.0,2012,1
4,2012-05-20T16:00:00Z,Corinthians-SP,SP,Fluminense-RJ,RJ,0.0,1.0,2012,1
5,2012-05-20T16:00:00Z,Botafogo-RJ,RJ,Sao Paulo-SP,SP,4.0,2.0,2012,1
6,2012-05-20T16:00:00Z,Internacional-RS,RS,Coritiba-PR,PR,2.0,0.0,2012,1
7,2012-05-20T18:30:00Z,Vasco da Gama-RJ,RJ,Gremio-RS,RS,2.0,1.0,2012,1
8,2012-05-20T18:30:00Z,Bahia-BA,BA,Santos-SP,SP,0.0,0.0,2012,1
9,2012-05-20T18:30:00Z,Cruzeiro-MG,MG,Atletico-GO,GO,0.0,0.0,2012,1

Informações técnias do dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3800 entries, 0 to 3799
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   datetime         3800 non-null   object
 1   home_team        3800 non-null   object
 2   home_team_state  3800 non-null   object
 3   away_team        3800 non-null   object
 4   away_team_state  3800 non-null   object
 5   home_goal        3799 non-null   float64
 6   away_goal        3799 non-null   float64
 7   season           3800 non-null   int64
 8   round            3800 non-null   int64
dtypes: float64(2), int64(2), object(5)
memory usage: 267.3+ KB
Valores ausentes por coluna
datetime           0
home_team          0
home_team_state    0
away_team          0
away_team_state    0
home_goal          1
away_goal          1
season             0
round              0
dtype: int64

In [9]:
df_limpo = df.dropna().copy()
df_limpo = df.drop_duplicates()

print('Valores nulos restantes')
print(df_limpo.isna().sum())

Valores nulos restantes
datetime           0
home_team          0
home_team_state    0
away_team          0
away_team_state    0
home_goal          1
away_goal          1
season             0
round              0
dtype: int64

In [18]:
df_limpo['datetime'] = pd.to_datetime(df_limpo['datetime'])
df_limpo['home_team'] = df_limpo['home_team'].str.strip()
df_limpo['away_team'] = df_limpo['away_team'].str.strip()
df_limpo = df_limpo.drop(columns=['season', 'round'])

KeyError: 'home_team'

In [23]:
df_limpo = df_limpo.rename(columns={'datetime': 'data_jogo'})
df_limpo = df_limpo.rename(columns={'home_team':'mandante'})
df_limpo = df_limpo.rename(columns={'away_team':'visitante'})
df_limpo = df_limpo.rename(columns={'home_team_state':'estado_mandante'})
df_limpo = df_limpo.rename(columns={'away_team_state':'estado_visitante'})
df_limpo = df_limpo.rename(columns={'home_goal':'gols_mandante'})
df_limpo = df_limpo.rename(columns={'away_goal':'gols_visitante'})

In [26]:
df_limpo['data_jogo'] = pd.to_datetime(df_limpo['data_jogo'])
df_limpo['mandante'] = df_limpo['mandante'].str.strip()
df_limpo['visitante'] = df_limpo['visitante'].str.strip()
df_limpo = df_limpo.drop(columns=['season', 'round'], errors='ignore')

In [29]:
df_limpo.head(10)

,data_jogo,mandante,estado_mandante,visitante,estado_visitante,gols_mandante,gols_visitante
0,2012-05-19 18:30:00+00:00,Palmeiras-SP,SP,Portuguesa-SP,SP,1.0,1.0
1,2012-05-19 18:30:00+00:00,Sport-PE,PE,Flamengo-RJ,RJ,1.0,1.0
2,2012-05-19 21:00:00+00:00,Figueirense-SC,SC,Nautico-PE,PE,2.0,1.0
3,2012-05-20 16:00:00+00:00,Ponte Preta-SP,SP,Atletico-MG,MG,0.0,1.0
4,2012-05-20 16:00:00+00:00,Corinthians-SP,SP,Fluminense-RJ,RJ,0.0,1.0
5,2012-05-20 16:00:00+00:00,Botafogo-RJ,RJ,Sao Paulo-SP,SP,4.0,2.0
6,2012-05-20 16:00:00+00:00,Internacional-RS,RS,Coritiba-PR,PR,2.0,0.0
7,2012-05-20 18:30:00+00:00,Vasco da Gama-RJ,RJ,Gremio-RS,RS,2.0,1.0
8,2012-05-20 18:30:00+00:00,Bahia-BA,BA,Santos-SP,SP,0.0,0.0
9,2012-05-20 18:30:00+00:00,Cruzeiro-MG,MG,Atletico-GO,GO,0.0,0.0

In [ ]:
# Limpando a variável data para o formato AAAA-MM-DD
df_limpo['data_jogo'] = pd.to_datetime(df_limpo['data_jogo']).dt.date
print(df_limpo['data_jogo'].head())

0    2012-05-19
1    2012-05-19
2    2012-05-19
3    2012-05-20
4    2012-05-20
Name: data_jogo, dtype: object